module.exports={
	root:'http://127.0.0.1:8080/',
	upload:'uploads',
	maxUpdate:12,
	blog:{
		name:'个人博客',
		author:'higher'
	},
	session:{
		key:'blog',
		secret:'blog',
		maxAge:20*60*1000
	},
	mongodb:'mongodb://localhost/test'
}